name: Setup

description: Setup CI environment.

inputs:
  javascript-utils:
    description: If true, it will also restore the cache of the javascript util packages.
    required: false

runs:
  using: composite
  steps:
    - name: Read current GitHub Actions cache version
      shell: bash
      run: |
        echo "CACHE_VERSION=$(< .github/.cache_version)" >> $GITHUB_ENV

    - name: Edit path for docker
      shell: bash
      run: |
        echo "PATH=$PATH:/usr/lib/dart/bin:/root/.pub-cache/bin:/root/.sdkman/candidates/sbt/current/bin:/root/.sdkman/candidates/java/current/bin:/root/.nvm/versions/node/v20.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/pip:/root/.local/bin:/usr/local/go/bin:/root/go/bin:/usr/share/dotnet" >> $GITHUB_ENV

    # JavaScript for monorepo and tooling
    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Restore Yarn
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir || '.yarn/cache' }}
        # let yarn handle the cache hash
        key: yarn-cache-${{ env.CACHE_VERSION }}

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}

    - name: Install JavaScript dependencies
      shell: bash
      run: yarn install

    - name: Build scripts
      shell: bash
      run: yarn workspace scripts build:cli

    # JavaScript client deps
    - name: Get yarn js-client cache directory path
      if: ${{ inputs.javascript-utils == 'true' }}
      shell: bash
      id: yarn-cache-dir-client
      run: echo "dir=$(cd clients/algoliasearch-client-javascript && yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Restore Yarn js-client
      if: ${{ inputs.javascript-utils == 'true' }}
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-client.outputs.dir || 'clients/algoliasearch-client-javascript/.yarn/cache' }}
        # let yarn handle the cache hash
        key: yarn-cache-client-${{ env.CACHE_VERSION }}

    - name: Cache js-client node modules
      if: ${{ inputs.javascript-utils == 'true' }}
      uses: actions/cache@v4
      with:
        path: clients/algoliasearch-client-javascript/node_modules
        key: node-modules-client-${{ env.CACHE_VERSION }}-${{ hashFiles('clients/algoliasearch-client-javascript/yarn.lock') }}

    - name: Install JavaScript client dependencies
      if: ${{ inputs.javascript-utils == 'true' }}
      shell: bash
      run: cd clients/algoliasearch-client-javascript && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
